apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: bp-deployment
  labels:
    app: bp
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: bp 
  # pod template
  template:
    metadata:
      labels:
        app: bp
    spec:
      # pod contains 1 container
      containers:
      - name: bp
        image: bpacregistry.azurecr.io/bpbe:v1
        imagePullPolicy: ifNotPresent
        imagePullSecrets:
        - name: acr-secret
        # container opens port 8080
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP        
        env:
        - name: Environment
          value: Dev
        - name: DatabaseSettings_ConnectionString
          valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: connection_string    
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m" 
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: bp-service
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: LoadBalancer
  ports:
    # Accept traffic sent to port 8080
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: bp
