# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildFE
  displayName: Build FE-image
  jobs:
  - job: Build
    displayName: Build-FE-CI
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockHub'
        repository: 'saturdaystar/bp-fe'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/FE/Dockerfile'
        tags: '$(tag)'

- stage: Build VAR file
  displayName: Build VAR file
  jobs:
  - job: Build-VAR-file
    displayName: Build VAR file
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      displayName: 'Build WAR file'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        containerRegistry: 'DockHub'
        repository: 'saturdaystar/bpbe'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
