version: '3.4'
services:
  bpbe:
    environment:
      - "DatabaseSettings:ConnectionString=mongodb://bpdb:27017"
    depends_on:
      - bp.db
    ports:
      - "8000:80"

  bp-fe:
    depends_on:
      - bp.db
      - bpbe
    ports:
      - "8001:80"

  bp.db:
    container_name: mango
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db