- name: Deploy bp platform
  hosts: webservers
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Install Kubernetes
      ansible.builtin.package:
        name: kubernetes
        state: present

    - name: Install kubectl
      ansible.builtin.package:
        name: kubectl
        state: present

    - name: Copy Kubernetes deployment file
      ansible.builtin.copy:
        src: k8s-deployment.yaml
        dest: /tmp/k8s-deployment.yaml

    - name: Deploy e-commerce services to Kubernetes
      ansible.builtin.command: kubectl apply -f /tmp/k8s-deployment.yaml
